apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        bunkerweb.io/component: "controller"
    spec:
      serviceAccountName: {{ include "bunkerweb.fullname" . }}
      containers:
        - name: bunkerweb-controller
          image: {{ .Values.controller.repository }}:{{ .Values.controller.tag }}
          imagePullPolicy: {{ .Values.controller.pullPolicy }}
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12}}
          {{- end }}
          env:
            # Mandatory for k8s integration
            - name: KUBERNETES_MODE
              value: "yes"
            - name: DATABASE_URI
              {{- if not (empty .Values.settings.existingSecret) }}
              secretKeyRef:
                name: {{ .Values.settings.existingSecret }}
                key: database-uri
              {{- else }}
              value: "{{ include "bunkerweb.databaseUri" . }}"
              {{- end }}
            - name: NAMESPACES
              value: "{{ .Values.settings.kubernetes.namespaces }}"
            - name: KUBERNETES_INGRESS_CLASS
              value: "{{ .Values.settings.kubernetes.ingressClass }}"
            - name: KUBERNETES_DOMAIN_NAME
              value: "{{ .Values.settings.kubernetes.domainName }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}