{{- if .Values.mariadb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        bunkerweb.io/component: "mariadb"
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          imagePullPolicy: Always
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "{{ .Values.mariadb.config.randomRootPassword }}"
            - name: MARIADB_DATABASE
              value: "{{ .Values.mariadb.config.database }}"
            - name: MARIADB_USER
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: mariadb-user
              {{- else }}
              value: "{{ .Values.mariadb.config.user }}"
              {{- end }}
            - name: MARIADB_PASSWORD
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: mariadb-password
              {{- else }}
              value: "{{ .Values.mariadb.config.password }}"
              {{- end }}
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: vol-db
      volumes:
        - name: vol-db
          persistentVolumeClaim:
            claimName: mariadb-{{ include "bunkerweb.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}